
== Introduction

=== Purpose of the software

openTCS is a control system/fleet management software for automatic vehicles.
It was primarily developed for the coordination of automated guided vehicles (AGV) performing transportation tasks e.g. in a production plant.
However, it can be used with other automatic vehicles like mobile robots or quadrocopters, too.
openTCS controls the vehicles independent of their specific characteristics like track guidance system or load handling device.
This is achieved by integrating vehicles into the system via pluggable drivers, similar to device drivers in operating systems.

=== System requirements

To run openTCS, a Java Runtime Environment (JRE) version 1.8 is required.
(The directory `bin` of the installed JRE, for example `C:/Program Files/Java/jre1.8.0/bin`, should be included in the enviroment variable PATH to be able to use the included start scripts.)

=== Further documentation

If you intend to extend and customize openTCS, please also see the Developer's Guide and the JavaDoc documentation that is part of the openTCS distribution.

=== Questions and problem reports

If you have questions about this manual, the openTCS project or about using or extending openTCS, please contact the development team by using the mailing list at http://sourceforge.net/projects/opentcs/.

If you encounter technical problems using openTCS, please remember to include enough data in your problem report to help the developers help you, e.g.:

* The applications' log files, contained in the subdirectory `log/` of both the kernel and the plant overview application
* The plant model you are working with, contained in the subdirectory `data/` of the kernel and/or plant overview application
