
== Introduction

=== Purpose of the software

openTCS (short for _open Transportation Control System_) is a free control system software for coordinating fleets of https://en.wikipedia.org/wiki/Automated_guided_vehicle[automated guided vehicles (AGVs)] and mobile robots, e.g. in production plants.
It should generally be possible to control any automatic vehicle with communication capabilities with it, but AGVs are the main target.

openTCS controls vehicles independent of their specific characteristics like navigation principle/track guidance system or load handling device.
It can manage vehicles of different types (and performing different tasks) at the same time.

openTCS itself is not a complete product you use out-of-the-box to control AGVs with.
Primarily, it is a framework/an implementation of the basic data structures and algorithms (routing of vehicles, dispatching orders to them, managing the fleet's traffic) needed for running an AGV system with more than one vehicle.
It tries to be as generic as possible to allow interoperation with vehicles of practically any vendor.

As a consequence, it is usually necessary to at least create and plug in a vehicle driver (called _communication adapter_ in openTCS-speak) that translates between the abstract interface of the openTCS kernel and the communication protocol your vehicle understands.
(Such vehicle drivers are similar to device drivers in operating systems, in a way.)
Depending on your needs, it might also be necessary to adapt algorithms or add project-specific strategies.

=== System requirements

openTCS does not come with any specific hardware requirements.
CPU power and RAM capacity highly depend on the use case, e.g. the size and complexity of the driving course and the number of vehicles managed.
Some kind of networking hardware -- in most cases simply a standard Ethernet controller -- is required for communicating with the vehicles (and possibly other systems, like a warehouse management system).

To run openTCS, a Java Runtime Environment (JRE) version 13 is required.
(The directory `bin` of the installed JRE, for example `C:\Program Files\AdoptOpenJDK\jdk-13.0.2.8-hotspot\bin`, should be included in the enviroment variable PATH to be able to use the included start scripts.)

IMPORTANT: Due to a limitation in a software library used by openTCS (namely: Docking Frames), some JREs are currently not compatible with openTCS.
This is true e.g. for the JRE provided by Oracle.
The recommended JRE to use is the one provided by the https://adoptium.net/[Adoptium project].

=== Licensing

openTCS is being maintained by the openTCS team at the https://www.iml.fraunhofer.de/[Fraunhofer Institute for Material Flow and Logistics].

The openTCS source code is licensed under the terms of the MIT License.
Please note that openTCS is distributed without any warranty - without even the implied warranty of merchantability or fitness for a particular purpose.
Please refer to the license (`LICENSE.txt`) for details.

=== Further documentation

If you intend to extend and customize openTCS, please also see the Developer's Guide and the JavaDoc documentation that is part of the openTCS distribution.

=== Support

Please note that, while Fraunhofer IML is happy to be able to release openTCS to the public as free software and would like to see it used and improved continuously, the development team cannot provide unlimited free support for it.

If you have technical/support questions, please post them on the project's discussion forum, where the community and the developers involved will respond as time permits.
You can find the discussion forum at https://github.com/openTCS/opentcs/discussions.
Please remember to include enough data in your problem report to help the developers help you, e.g.:

* The applications' log files, contained in the subdirectory `log/` of the kernel, kernel control center, model editor and operations desk application
* The plant model you are working with, contained in the subdirectory `data/` of the kernel and/or model editor application
