
== Advanced usage

=== Attaching vehicle drivers automatically on startup

Manually attaching drivers to the vehicles in a plant model allows you to explicitly select the driver for each vehicle from the list of available
drivers, which can be useful during development.
In a productive environment, however, such manual steps are usually undesired.
In order to automatically attach matching drivers to all vehicles in a plant model, you can do the following:

. Start the kernel.
. Select the plant model.
. Select plant operation mode.
. Switch to the Vehicle drivers tab in the kernel control center.
. Right-click on the vehicles list and select menu:Startup options[Auto-attach all].
This will let openTCS automatically attach drivers to all vehicles in the list when you start the kernel for plant operation.
. Right-click on the vehicles list again and select menu:Startup options[Enable all].
This will result in the vehicle drivers also being enabled automatically on startup.
. From the kernel control center's main menu, select menu:Settings[Save settings] to persist the selected startup options.

=== Initializing a virtual vehicle's position automatically on startup

Even during the development or simulation phase of a project, repeatedly setting a virtual vehicle's initial position manually via the loopback driver's user interface can be tiresome and possibly error-prone.
To automatically set a vehicle's initial position when the loopback driver is enabled, you can store the initial position in the respective plant model by doing the following:

. Start the plant overview client in modelling mode.
. In the plant overview client's tree view of the plant model, select a vehicle.
. In the table showing the vehicle's properties, click into the value field labelled btn:[Initial position].
In the dialog shown, select the initial position for this vehicle from the model's list of points.
. Save the model and persist it in the kernel as described in <<Saving the plant model>>.

Whenever you attach the loopback driver to the modified vehicle after doing this, it will automatically report the vehicle's position to be the one that you selected.

=== Using model element properties for project-specific data

Every object in the plant model - i.e. points, paths, locations, location types and vehicles - can be augmented with arbitrary project-specific data that can be used, e.g. by vehicle drivers, custom client applications, etc..
Possible uses for such data could be informing the vehicle driver about additional actions to be performed by a vehicle when moving along a path in the model (e.g. flashing direction indicators, displaying a text string on a display, giving an acoustic warning) or controlling the behaviour of peripheral systems (e.g. automatic fire protection gates).

The data can be stored in properties, i.e. key-value pairs attached to the model elements, where both the key and the corresponding value are text strings.
These key-value pairs can be created and edited using the plant overview client:
Simply select the model element you want to add a key-value pair to and click into the value field labelled btn:[Miscellaneous] in the properties table.
In the dialog shown, set the key-value pairs you need to store your project-specific information.

NOTE: For your project-specific key-value pairs, you may specify arbitrary keys.
openTCS itself will not make any use of this data; it will merely store it and provide it for custom vehicle drivers and/or other extensions.
You should, however, not use any keys starting with `"tcs:"` for storing project-specific data.
Any keys with this prefix are reserved for official openTCS features, and using them could lead to collisions.

=== Manipulating the system configuration

These instructions demonstrate how system parameters that influence e.g. the routing or parking strategies, can be manipulated.

==== Selecting the cost factors used for routing

. Switch to the kernel control center's btn:[Configuration] tab.
. Find and select the configuration entry `org.opentcs.strategies.basic.routing.DefaultRouter.routingCostFactors` and click the btn:[Configure] button.
* This entry only appears after the kernel has been run in operating mode at least once before.
If it is missing with you, switch the kernel to operating mode once and restart it.
. In the dialog shown, set the configuration item's value to one or more (separated by blanks and/or commas) of the following key words:
* `hops`: Routing costs are measured by the number of hops/paths travelled along the route.
* `distance`: Routing costs are measured by the sum of the lengths of paths travelled.
* `traveltime`: Routing costs are measured by the sum of the times required for travelling each path on a route.
The travel times are computed using the length of the respective path and the maximum speed with which a vehicle may move on it.
* `turns`: Routing costs are measured by the number of changes of the vehicle's orientation on a route.
To specify an orientation for a vehicle on a path, set a property on that path with a key of `"tcs:travelOrientation"` and an arbitrary string as the value.
If, and only if, the values of subsequent paths on a route differ, a penalty is added to the costs of that route.
This penalty can be configured by setting the configuration entry `org.opentcs.kernel.module.routing.RouteEvaluatorTurns.penaltyPerTurn` to an integer value (default: 5000).
* `explicit`: Routing costs are measured by the sum of the costs explicitly specified by the modelling user.
Explicit costs can be specified for every single path in the model using the plant overview client.
(Select a path and set its btn:[Costs] property to an arbitrary integer value.)
. Shut down and restart the kernel for the changes to take effect.

NOTE: When specifying more than one of these key words, the respective costs computed are added up.
For example, when set to `"distance, turns"` (which is the default value), costs for routes are computed as the sum of the paths' lengths and the penalties for orientation changes.

==== Configuring automatic parking

===== Activating/deactivating automatic parking of idle vehicles

. Switch to the kernel control center's btn:[Configuration] tab.
. Find and select the configuration entry `org.opentcs.strategies.basic.dispatching.DefaultDispatcher.parkIdleVehicles` and click the btn:[Configure] button.
. Set the configuration item's value to `true` (activated) or `false` (deactivated).

==== Configuring order pool cleanup

By default, openTCS checks every minute for finished or failed transport orders that are older than 24 hours.
These orders are removed from the pool.
To customize this behaviour, the following steps are required:

. Switch to the kernel control center's btn:[Configuration] tab.
. Find and select the configuration entry `org.opentcs.kernel.OrderCleanerTask.orderSweepInterval`.
The default value is 60.000 (milliseconds, corresponding to an interval of one minute).
Set this value according to your needs.
. Find and select the configuration entry `org.opentcs.kernel.OrderCleanerTask.orderSweepAge` to change the maximum age of finished orders.
The default value is 86.400.000 (milliseconds, corresponding to 24 hours that a finished order should be kept in the pool).
Set this value according to your needs.
