
== Default strategies

openTCS comes with a default implementation for each of the strategy modules.
These implementations can easily be replaced to adapt to project-specific requirements.
(See developer's guide.)

=== Default dispatcher

When a transport order becomes dispatchable, the dispatcher needs to decide which vehicle should process it.
To make this decision, the default dispatcher takes the following steps:

. The default dispatcher checks which vehicles are available and not currently processing a transport order.
  If there are no such vehicles, the incoming transport order is postponed without a vehicle assignment.
. The default dispatcher requests the potential routes from the router for all vehicle candidates in case they were selected for the incoming transport order.
  If no viable route is available for any of the vehicles, the incoming transport order is postponed without a vehicle assignment.
. From all vehicles with viable routes, the one with the lowest routing costs is assigned to the incoming transport order.

When a vehicle becomes available, the dispatcher needs to decide which transport order it should process.
To make this decision, the default dispatcher takes the following steps:

. If the vehicle's energy level is not _critical_ and transport orders are available, the default dispatcher will select the most urgent one (according to its deadline) for which a route can be computed.
. If the vehicle's energy level is _degraded_ and automatic recharging is enabled, an order is created for the vehicle to recharge at a recharging location.
. If the vehicle is not currently at a parking position and there are unoccupied parking positions, an order is created for the vehicle to move to one of them.
. If none of the previous steps assigned an order to the vehicle, it is left at its current position.

When sending a vehicle to a recharge location or parking position, the closest (according to the router) unoccupied position is selected by default.
It is possible to assign fixed positions to vehicles instead, by setting properties with the following keys on them:

* `tcs:preferredParkingPosition`:
  Expected to be the name of a point in the model.
  If this point is already occupied, the closest unoccupied parking position (if any) is selected instead.
* `tcs:assignedParkingPosition`:
  Expected to be the name of a point in the model.
  If this point is already occupied, the vehicle is not sent to any other parking position, i.e. remains where it is.
  Takes precedence over `tcs:preferredParkingPosition`.
* `tcs:preferredRechargeLocation`:
  Expected to be the name of a location.
  If this location is already occupied, the closest unoccupied recharging location (if any) is selected instead.
* `tcs:assignedRechargeLocation`:
  Expected to be the name of a location.
  If this location is already occupied, the vehicle is not sent to any other recharging location.
  Takes precedence over `tcs:preferredRechargeLocation`.

=== Default router

The default router finds the cheapest route from one position in the driving course to another one.
(It uses an implementation of link:https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm[Dijkstra's algorithm] to do that.)
It takes into account paths that have been locked, but not positions and/or assumed future behaviour of other vehicles.
As a result, it does not route around slower or stopped vehicles blocking the way.

The cost function used for evaluating the edges of the graph can be configured -- see <<Default router configuration entries>>.
The default cost function for a path simply evaluates to the path's length, so the cheapest route by default is the shortest one.

It is possible to treat vehicles in a plant differently when computing their routes.
This may be desirable if they have different characteristics and actually have different optimal routes through the driving course.
For this to work, the paths in the model or the cost function used need to reflect reflect this difference.
This isn't done by default -- the default router computes routes for all vehicles the same way unless told otherwise.
To let the router know that it should compute routes for a vehicle separately, set a property with the key `tcs:routingGroup` to an integer value other than zero.
(Vehicles that have the same integer value set share the same routing table, and zero is the default value for all vehicles.)

=== Default scheduler

The default scheduler implements a simple strategy for traffic management.
It does this by allowing only mutually exclusive use of resources in the plant model (points and paths, primarily):

* When an allocation of a set of resources for a vehicle is requested, the scheduler expands this set to the effective resource set (in case any resources are part of a block area) and checks whether the allocation can be granted immediately.
  If yes, the allocation is made.
  If not, the allocation is queued for later.
* Whenever resources are freed (e.g. when a vehicle has finished its movement to the next point and the vehicle driver reports this to the kernel), the allocations waiting in the queue are checked (in the order the requests happened).
  Any allocations that can now be made are made.
  Allocations that cannot be made are kept waiting.

This strategy ensures that resources are used when they are available.
It does not, however, strictly ensure fairness/avoid starvation:
Vehicles waiting for allocation of a large resource set may theoretically wait forever if other vehicles can keep allocating subsets of those resources continuously.
Such situations are likely a hint at problems in the plant model graph's topology, which is why this deficiency is considered acceptable for the default implementation.
