== Configuring openTCS

=== Application language

By default, all openTCS applications with user interfaces display texts in English language.
The applications are prepared for internationalization, though, and can be configured to display texts in a different language, provided there is a translation for it.
The openTCS distribution comes with the default (English) language and a German translation.
Additional translations can be integrated -- how this is done is described in the Developer's Guide.

For setting the language, each application has a configuration entry that needs to be set to a _language tag_ for the language to use.
(See <<Kernel Control Center application configuration entries>>, <<Model Editor application configuration entries>> and <<Operations Desk application configuration entries>>.)
Examples for language tags are:

* "en" for English
* "de" for German
* "no" for Norwegian
* "zh" for Chinese

By default, the configuration entries are set to "en", resulting in English texts.
Since a German translation is included, you can switch e.g. the Operations Desk application to German by setting its `locale` configuration entry to "de".
(Note that the application needs to be restarted for this.)

Configuring an application to use a language for which there is no translation will result in the default (English) language to be used.

=== Kernel configuration

The kernel application reads its configuration data from the following files:

. `config/opentcs-kernel-defaults-baseline.properties`,
. `config/opentcs-kernel-defaults-custom.properties` and
. `config/opentcs-kernel.properties`.

The files are read in this order, and configuration values set in one file can be overridden in any subsequent one.
For users, it is recommended to leave the first two files untouched and set overriding values and project-specific configuration data in `opentcs-kernel.properties` only.

==== Kernel application configuration entries

The kernel application itself can be configured using the following configuration entries:

include::{configdoc}/KernelApplicationConfigurationEntries.adoc[]

==== Order pool configuration entries

The kernel's transport order pool can be configured using the following configuration entries:

include::{configdoc}/OrderPoolConfigurationEntries.adoc[]

==== Default dispatcher configuration entries

The default dispatcher can be configured using the following configuration entries:

include::{configdoc}/DefaultDispatcherConfigurationEntries.adoc[]

==== Default router configuration entries

The default router can be configured using the following configuration entries:

include::{configdoc}/DefaultRouterConfigurationEntries.adoc[]

The shortest path algorithm can be configured using the following configuration entries:

include::{configdoc}/ShortestPathConfigurationEntries.adoc[]

The edge evaluator `EXPLICIT_PROPERTIES` can be configured using the following configuration entries:

include::{configdoc}/ExplicitPropertiesConfigurationEntries.adoc[]

==== Default peripheral job dispatcher configuration entries

The default peripheral job dispatcher can be configured using the following configuration entries:

include::{configdoc}/DefaultPeripheralJobDispatcherConfigurationEntries.adoc[]

==== Admin web API configuration entries

The kernel's admin web API can be configured using the following configuration entries:

include::{configdoc}/AdminWebApiConfigurationEntries.adoc[]

==== Service web API configuration entries

The kernel's service web API can be configured using the following configuration entries:

include::{configdoc}/ServiceWebApiConfigurationEntries.adoc[]

==== RMI kernel interface configuration entries

The kernel's RMI interface can be configured using the following configuration entries:

include::{configdoc}/RmiKernelInterfaceConfigurationEntries.adoc[]

==== SSL server-side encryption configuration entries

The kernel's SSL encryption can be configured using the following configuration entries:

include::{configdoc}/KernelSslConfigurationEntries.adoc[]

==== Virtual vehicle configuration entries

The virtual vehicle (loopback communication adapter) can be configured using the following configuration entries:

include::{configdoc}/VirtualVehicleConfigurationEntries.adoc[]

==== Virtual peripheral configuration entries

The virtual peripheral (peripheral loopback communication adapter) can be configured using the following configuration entries:

include::{configdoc}/VirtualPeripheralConfigurationEntries.adoc[]

=== Kernel Control Center configuration

The kernel control center application reads its configuration data from the following files:

. `config/opentcs-kernelcontrolcenter-defaults-baseline.properties`,
. `config/opentcs-kernelcontrolcenter-defaults-custom.properties` and
. `config/opentcs-kernelcontrolcenter.properties`.

The files are read in this order, and configuration values set in one file can be overridden in any subsequent one.
For users, it is recommended to leave the first two files untouched and set overriding values and project-specific configuration data in `opentcs-kernelcontrolcenter.properties` only.

==== Kernel Control Center application configuration entries

The kernel control center application itself can be configured using the following configuration entries:

include::{configdoc}/KernelControlCenterApplicationConfigurationEntries.adoc[]

==== SSL KCC-side application configuration entries

The kernel control center application's SSL connections can be configured using the following configuration entries:

include::{configdoc}/KccSslConfigurationEntries.adoc[]

=== Model Editor configuration

The model editor application reads its configuration data from the following files:

. `config/opentcs-modeleditor-defaults-baseline.properties`,
. `config/opentcs-modeleditor-defaults-custom.properties`,
. `config/opentcs-modeleditor.properties`.

The files are read in this order, and configuration values set in one file can be overridden in any subsequent one.
For users, it is recommended to leave the first two files untouched and set overriding values and project-specific configuration data in `opentcs-modeleditor.properties` only.

NOTE: Some of the following configuration entries still use the prefix 'plantoverviewapp', which is reminiscent of the old plant overview application.
With openTCS 6.0, the prefix 'plantoverviewapp' will be replaced with one more suitable for the new model editor application.

==== Model Editor application configuration entries

The model editor application itself can be configured using the following configuration entries:

include::{configdoc}/PlantOverviewApplicationConfigurationEntries.adoc[]
include::{configdoc}/PlantOverviewModelingApplicationConfigurationEntries.adoc[]

==== SSL model editor-side application configuration entries

The model editor application's SSL connections can be configured using the following configuration entries:

include::{configdoc}/PoSslConfigurationEntries.adoc[]

==== Model Editor element naming scheme configuration entries

The model editor application's element naming schemes can be configured using the following configuration entries:

include::{configdoc}/PO_ElementNamingSchemeConfigurationEntries.adoc[]

=== Operations Desk configuration

The operations desk application reads its configuration data from the following files:

. `config/opentcs-operationsdesk-defaults-baseline.properties`,
. `config/opentcs-operationsdesk-defaults-custom.properties`,
. `config/opentcs-operationsdesk.properties`.

The files are read in this order, and configuration values set in one file can be overridden in any subsequent one.
For users, it is recommended to leave the first two files untouched and set overriding values and project-specific configuration data in `opentcs-operationsdesk.properties` only.

NOTE: Some of the following configuration entries still use the prefix 'plantoverviewapp', which is reminiscent of the old plant overview application.
With openTCS 6.0, the prefix 'plantoverviewapp' will be replaced with one more suitable for the new operations desk application.

==== Operations Desk application configuration entries

The operations desk application itself can be configured using the following configuration entries:

include::{configdoc}/PlantOverviewApplicationConfigurationEntries.adoc[]
include::{configdoc}/PlantOverviewOperatingApplicationConfigurationEntries.adoc[]

==== SSL operation desk-side application configuration entries

The operation desk application's SSL connections can be configured using the following configuration entries:

include::{configdoc}/PoSslConfigurationEntries.adoc[]
