
== Configuring openTCS

=== Kernel configuration

The kernel application reads its configuration data from two files -- `config/opentcs-kernel-defaults.properties` and `config/opentcs-kernel.properties`.
(Both files must exist.)
It is good practice to leave the first one untouched and set overriding values and project-specific configuration data in the second one.

==== Kernel application configuration entries

The kernel application itself can be configured using the following configuration entries:

include::{configdoc}/KernelApplicationConfigurationEntries.adoc[]

==== Control center configuration entries

The kernel's control center GUI can be configured using the following configuration entries:

include::{configdoc}/ControlCenterConfigurationEntries.adoc[]

==== Order pool configuration entries

The kernel's transport order pool can be configured using the following configuration entries:

include::{configdoc}/OrderPoolConfigurationEntries.adoc[]

==== Vehicle communication configuration entries

General communication with vehicles can be configured using the following configuration entries:

include::{configdoc}/VehiclesConfigurationEntries.adoc[]

==== Default dispatcher configuration entries

The default dispatcher can be configured using the following configuration entries:

include::{configdoc}/DefaultDispatcherConfigurationEntries.adoc[]

==== Default router configuration entries

The default router can be configured using the following configuration entries:

include::{configdoc}/DefaultRouterConfigurationEntries.adoc[]

The shortest path algorithm can be configured using the following configuration entries:

include::{configdoc}/ShortestPathConfigurationEntries.adoc[]

==== RMI kernel interface configuration entries

The kernel's RMI interface can be configured using the following configuration entries:

include::{configdoc}/RmiKernelInterfaceConfigurationEntries.adoc[]

==== XML host interface configuration entries

The kernel's XML-based host interface can be configured using the following configuration entries:

include::{configdoc}/XMLHostInterfaceConfigurationEntries.adoc[]

==== Virtual vehicle configuration entries

The virtual vehicle (loopback communication adapter) can be configured using the following configuration entries:

include::{configdoc}/VirtualVehicleConfigurationEntries.adoc[]

=== Plant Overview configuration

The plant overview application reads its configuration data from two files -- `config/opentcs-plantoverview-defaults.properties` and `config/opentcs-plantoverview.properties`.
(Both files must exist.)
It is good practice to leave the first one untouched and set overriding values and project-specific configuration data in the second one.

==== Plant Overview application configuration entries

The plant overview application itself can be configured using the following configuration entries:

include::{configdoc}/PlantOverviewApplicationConfigurationEntries.adoc[]
