
== Configuring openTCS

=== Kernel configuration

The kernel application reads its configuration data from two files -- `config/opentcs-kernel-defaults-baseline.properties` and `config/opentcs-kernel.properties`.
It is good practice to leave the first one untouched and set overriding values and project-specific configuration data in the second one.

==== Kernel application configuration entries

The kernel application itself can be configured using the following configuration entries:

include::{configdoc}/KernelApplicationConfigurationEntries.adoc[]

==== Control center configuration entries

The kernel's control center GUI can be configured using the following configuration entries:

include::{configdoc}/ControlCenterConfigurationEntries.adoc[]

==== Order pool configuration entries

The kernel's transport order pool can be configured using the following configuration entries:

include::{configdoc}/OrderPoolConfigurationEntries.adoc[]

==== Default dispatcher configuration entries

The default dispatcher can be configured using the following configuration entries:

include::{configdoc}/DefaultDispatcherConfigurationEntries.adoc[]

==== Default router configuration entries

The default router can be configured using the following configuration entries:

include::{configdoc}/DefaultRouterConfigurationEntries.adoc[]

The shortest path algorithm can be configured using the following configuration entries:

include::{configdoc}/ShortestPathConfigurationEntries.adoc[]

==== Admin web API configuration entries

The kernel's admin web API can be configured using the following configuration entries:

include::{configdoc}/AdminWebApiConfigurationEntries.adoc[]

==== Service web API configuration entries

The kernel's service web API can be configured using the following configuration entries:

include::{configdoc}/ServiceWebApiConfigurationEntries.adoc[]

==== RMI kernel interface configuration entries

The kernel's RMI interface can be configured using the following configuration entries:

include::{configdoc}/RmiKernelInterfaceConfigurationEntries.adoc[]

==== XML host interface configuration entries

The kernel's XML-based host interface can be configured using the following configuration entries:

include::{configdoc}/XMLHostInterfaceConfigurationEntries.adoc[]

==== SSL server-side encryption configuration entries

The kernel's SSL encryption can be configured using the following configuration entries:

include::{configdoc}/KernelSslConfigurationEntries.adoc[]

==== Statistics collector configuration entries

The kernel's statistics collector can be configured using the following configuration entries:

include::{configdoc}/StatisticsCollectorConfigurationEntries.adoc[]

==== Virtual vehicle configuration entries

The virtual vehicle (loopback communication adapter) can be configured using the following configuration entries:

include::{configdoc}/VirtualVehicleConfigurationEntries.adoc[]

=== Kernel Control Center configuration

The kernel control center application reads its configuration data from two files -- `config/opentcs-kernelcontrolcenter-defaults-baseline.properties` and `config/opentcs-kernelcontrolcenter.properties`.
It is good practice to leave the first one untouched and set overriding values and project-specific configuration data in the second one.

==== Kernel Control Center application configuration entries

The kernel control center application itself can be configured using the following configuration entries:

include::{configdoc}/KernelControlCenterApplicationConfigurationEntries.adoc[]

==== SSL KCC-side application configuration entries

The kernel control center application's SSL connections can be configured using the following configuration entries:

include::{configdoc}/KccSslConfigurationEntries.adoc[]

=== Plant Overview configuration

The plant overview application reads its configuration data from two files -- `config/opentcs-plantoverview-defaults-baseline.properties` and `config/opentcs-plantoverview.properties`.
It is good practice to leave the first one untouched and set overriding values and project-specific configuration data in the second one.

==== Plant Overview application configuration entries

The plant overview application itself can be configured using the following configuration entries:

include::{configdoc}/PlantOverviewApplicationConfigurationEntries.adoc[]

==== SSL PO-side application configuration entries

The plant overview application's SSL connections can be configured using the following configuration entries:

include::{configdoc}/PoSslConfigurationEntries.adoc[]
