
== Advanced usage examples

=== Configuring automatic startup

. To have the kernel automatically load a plant model on startup, set the kernel application's configuration parameter `kernelapp.loadModelOnStartup` to `true`.
. To suppress the startup dialog that is normally shown by the kernel application on startup, set its configuration parameter `kernelapp.selectModelOnStartup` to `false`.
. For automatic attachment of vehicle drivers to vehicles on startup, set the kernel application's configuration parameter `kernelapp.autoAttachDriversOnStartup` to `true`.
. To automatically enable vehicle drivers on startup, set the kernel application's configuration parameter `kernelapp.autoEnableDriversOnStartup` to `true`.

=== Automatically selecting a specific vehicle driver on startup

Automatic attachment of vehicle drivers by default works as follows:
The kernel asks every available vehicle driver if it can attach to a given vehicle and selects the first one that can.
It asks the loopback driver last, as that one is always available and can attach to any vehicle, but should not prevent actual vehicle drivers to be attached.
As a result, if there is only one driver for your vehicle(s), you usually do not have to do anything for it to be selected.

In some less common cases, you may have multiple vehicle drivers registered with the kernel that can all attach to the vehicles in your plant model.
To automatically select a specific driver in such cases, set a property with the key `tcs:preferredAdapterClass` on the vehicles, with its value being the name of the Java class implementing the driver's adapter factory.
(If you do not know this class name, ask the developer who provided the vehicle driver to you for it.)

=== Configuring a virtual vehicle's characteristics

The loopback driver supports some (limited) configuration of the virtual vehicle's characteristics via properties set in the plant model.
You can set the properties the following way:

. Start the plant overview client in modelling mode and create or load a plant model.
. In the plant overview client's tree view of the plant model, select a vehicle.
. In the table showing the vehicle's properties, click into the value field labelled btn:[Miscellaneous].
  In the dialog shown, add a property key and value according to the list below.
. Save the model and persist it in the kernel as described in <<Saving the plant model>>.

The loopback driver interprets properties with the following keys:

* `loopback:initialPosition`:
  Set the property value to the name of a point in the plant model.
  When started, the loopback adapter will set the virtual vehicle's current position to this.
  (Default value: not set)
* `loopback:acceleration`:
  Set the property value to a positive integer representing an acceleration in mm/s^2^.
  The loopback adapter will simulate vehicle movement with the given acceleration.
  (Default value: 500)
* `loopback:deceleration`:
  Set the property value to a negative integer representing an acceleration in mm/s^2^.
  The loopback adapter will simulate vehicle movement with the given deceleration.
  (Default value: -500)
* `loopback:loadOperation`:
  Set the property value to a string representing the virtual vehicle's load operation.
  When the virtual vehicle executes this operation, the loopback adapter will set the its load handling device's state to _full_.
  (Default value: not set)
* `loopback:unloadOperation`:
  Set the property value to a string representing the virtual vehicle's unload operation.
  When the virtual vehicle executes this operation, the loopback adapter will set its load handling device's state to _empty_.
  (Default value: not set)
* `loopback:operatingTime`:
  Set the property value to a positive integer representing the virtual vehicle's operating time in milliseconds.
  When the virtual vehicle executes an operation, the loopback adapter will simulate an operating time accordingly.
  (Default value: 5000)

=== Running kernel and plant overview on separate systems

The kernel and the plant overview client communicate via Java's Remote Method Invocation (RMI) mechanism.
This makes it possible to run the kernel and the plant overview client on separate systems, as long as a network connection between these systems exists and is usable.

By default, the plant overview client is configured to connect to a kernel running on the same system.
To connect it to a kernel running on a remote system, e.g. on a host named myhost.example.com, set the plant overview application's configuration parameter `plantoverviewapp.connectionBookmarks` to `myhost.example.com:1099`.
The configuration value can be a comma-separated list of host:port pairs.
The plant overview will automatically try to connect to the first host in the list.
If that fails, it will show a dialog to select an entry or enter a different address.

=== Configuring automatic parking and recharging

By default, idle vehicles remain where they are after processing their last transport order.
You can change this in the kernel's configuration file:

* To order vehicles to charging locations automatically, set the configuration parameter `defaultdispatcher.rechargeIdleVehicles` to `true`.
  The default dispatcher will then look for locations at which the idle vehicle's recharge operation is possible and create orders to send it to such a location (if unoccupied).
  (Note that the string used for the operation is driver-specific.)
* To order vehicles to parking positions automatically, set the configuration parameter `defaultdispatcher.parkIdleVehicles` to `true`.
  The default dispatcher will then look for unoccupied parking positions and create orders to send the idle vehicle there.

=== Selecting the cost factors used for routing

The default router can evaluate the costs for routes based on different factors.
You can select which factors should be taken into account by setting the configuration parameter `defaultrouter.routeEvaluators` in the kernel's configuration file to one or more of the following key words (separated by commas):

* `HOPS`: Routing costs are measured by the number of hops/paths travelled along the route.
* `DISTANCE`: Routing costs are measured by the sum of the lengths of paths travelled.
* `TRAVELTIME`: Routing costs are measured by the sum of the times required for travelling each path on a route.
The travel times are computed using the length of the respective path and the maximum speed with which a vehicle may move on it.
* `TURNS`: Routing costs are measured by the number of changes of the vehicle's orientation on a route.
  To specify an orientation for a vehicle on a path, set a property on that path with a key of `"tcs:travelOrientation"` and an arbitrary string as the value.
  If, and only if, the values of subsequent paths on a route differ, a penalty is added to the costs of that route.
  This penalty can be configured by setting the configuration entry `defaultrouter.turnCosts` to an integer value (default: 5000).
* `EXPLICIT`: Routing costs are measured by the sum of the costs explicitly specified by the modelling user.
  Explicit costs can be specified for every single path in the model using the plant overview client.
  (Select a path and set its btn:[Costs] property to an arbitrary integer value.)

NOTE: When specifying more than one of these key words, the respective costs computed are added up.
For example, when set to `"DISTANCE, TURNS"`, costs for routes are computed as the sum of the paths' lengths and the penalties for orientation changes.
If none of these entries is set, costs for routes are computed by the paths' lengths by default (`DISTANCE`).

=== Configuring order pool cleanup

By default, openTCS checks every minute for finished or failed transport orders that are older than 24 hours.
These orders are removed from the pool.
To customize this behaviour, do the following:

. Set the configuration entry `orderpool.sweepInterval` to a value according to your needs.
  The default value is 60.000 (milliseconds, corresponding to an interval of one minute).
. Set the configuration entry `orderpool.sweepAge` to a maximum age of finished orders according to your needs.
  The default value is 86.400.000 (milliseconds, corresponding to 24 hours that a finished order should be kept in the pool).

=== Using model element properties for project-specific data

Every object in the plant model - i.e. points, paths, locations, location types and vehicles - can be augmented with arbitrary project-specific data that can be used, e.g. by vehicle drivers, custom client applications, etc..
Possible uses for such data could be informing the vehicle driver about additional actions to be performed by a vehicle when moving along a path in the model (e.g. flashing direction indicators, displaying a text string on a display, giving an acoustic warning) or controlling the behaviour of peripheral systems (e.g. automatic fire protection gates).

The data can be stored in properties, i.e. key-value pairs attached to the model elements, where both the key and the corresponding value are text strings.
These key-value pairs can be created and edited using the plant overview client:
Simply select the model element you want to add a key-value pair to and click into the value field labelled btn:[Miscellaneous] in the properties table.
In the dialog shown, set the key-value pairs you need to store your project-specific information.

NOTE: For your project-specific key-value pairs, you may specify arbitrary keys.
openTCS itself will not make any use of this data; it will merely store it and provide it for custom vehicle drivers and/or other extensions.
You should, however, not use any keys starting with `"tcs:"` for storing project-specific data.
Any keys with this prefix are reserved for official openTCS features, and using them could lead to collisions.
