
== Advanced usage examples

=== Configuring automatic startup

. To automatically enable vehicle drivers on startup, set the kernel application's configuration parameter `kernelapp.autoEnableDriversOnStartup` to `true`.

=== Automatically selecting a specific vehicle driver on startup

Automatic attachment of vehicle drivers by default works as follows:
The kernel asks every available vehicle driver if it can attach to a given vehicle and selects the first one that can.
It asks the loopback driver last, as that one is always available and can attach to any vehicle, but should not prevent actual vehicle drivers to be attached.
As a result, if there is only one driver for your vehicle(s), you usually do not have to do anything for it to be selected.

In some less common cases, you may have multiple vehicle drivers registered with the kernel that can all attach to the vehicles in your plant model.
To automatically select a specific driver in such cases, set a property with the key `tcs:preferredAdapterClass` on the vehicles, with its value being the name of the Java class implementing the driver's adapter factory.
(If you do not know this class name, ask the developer who provided the vehicle driver to you for it.)

=== Configuring a virtual vehicle's characteristics

The loopback driver supports some (limited) configuration of the virtual vehicle's characteristics via properties set in the plant model.
You can set the properties the following way:

. Start the plant overview client in modelling mode and create or load a plant model.
. In the plant overview client's tree view of the plant model, select a vehicle.
. In the table showing the vehicle's properties, click into the value field labelled btn:[Miscellaneous].
  In the dialog shown, add a property key and value according to the list below.
. Save the model and persist it in the kernel as described in <<Saving the plant model>>.

The loopback driver interprets properties with the following keys:

* `loopback:initialPosition`:
  Set the property value to the name of a point in the plant model.
  When started, the loopback adapter will set the virtual vehicle's current position to this.
  (Default value: not set)
* `loopback:acceleration`:
  Set the property value to a positive integer representing an acceleration in mm/s^2^.
  The loopback adapter will simulate vehicle movement with the given acceleration.
  (Default value: 500)
* `loopback:deceleration`:
  Set the property value to a negative integer representing an acceleration in mm/s^2^.
  The loopback adapter will simulate vehicle movement with the given deceleration.
  (Default value: -500)
* `loopback:loadOperation`:
  Set the property value to a string representing the virtual vehicle's load operation.
  When the virtual vehicle executes this operation, the loopback adapter will set the its load handling device's state to _full_.
  (Default value: not set)
* `loopback:unloadOperation`:
  Set the property value to a string representing the virtual vehicle's unload operation.
  When the virtual vehicle executes this operation, the loopback adapter will set its load handling device's state to _empty_.
  (Default value: not set)
* `loopback:operatingTime`:
  Set the property value to a positive integer representing the virtual vehicle's operating time in milliseconds.
  When the virtual vehicle executes an operation, the loopback adapter will simulate an operating time accordingly.
  (Default value: 5000)

=== Running kernel and its clients on separate systems

The kernel and its clients (plant overview client and kernel control center client) communicate via Java's Remote Method Invocation (RMI) mechanism.
This makes it possible to run the kernel and the clients on separate systems, as long as a network connection between these systems exists and is usable.

By default, both, the plant overview client and the kernel control center client are configured to connect to a kernel running on the same system.
To connect them to a kernel running on a remote system, e.g. on a host named myhost.example.com, set the plant overview application's configuration parameter `plantoverviewapp.connectionBookmarks` and the kernel control center's application configuration parameter `kernelcontrolcenter.connectionBookmarks` to `SomeDescription|myhost.example.com|1099`.
The configuration value can be a comma-separated list of <description>|<host>|<port> sets.
The plant overview client and kernel control center client will automatically try to connect to the first host in the list.
If that fails, they will show a dialog to select an entry or enter a different address.

=== Encrypting communication with the kernel

By default, client applications and the kernel communicate via plain Java Remote Method Invocation (RMI) calls or HTTP requests.
These communication channels can optionally be encrypted via SSL/TLS.
To achieve this, do the following:

. Generate a keystore/truststore pair (`keystore.p12` and `truststore.p12`).
.. You can use the Unix shell script or Windows batch file (`generateKeystores.sh/.bat`) provided in the kernel application's directory for this.
.. The scripts use the key and certificate management tool 'keytool' that is included in both the Java JDK and JRE.
   If 'keytool' is not contained in the system's `Path` environment variable the `KEYTOOL_PATH` variable in the respective script needs to be modified to point to the location where the 'keytool' is located.
.. By default, the generated files are placed in the kernel application's `config` directory.
. Copy the `truststore.p12` file to the client application's (plant overview and/or kernel control center) `config` directory.
  Leave the file in the kernel application's `config` directory as well.
. In the kernel's configuration file, enable SSL for the RMI interface and/or for the web service interface.
  (See <<RMI kernel interface configuration entries>> and/or <<Service web API configuration entries>> for a description of the configuration entries.)
. If you enabled SSL for the RMI interface, you need to enable it in the Plant Overview's and the Kernel Control Center's configuration files, too.
  (See <<SSL PO-side application configuration entries>> and <<SSL KCC-side application configuration entries>> for a description of the configuration entries.)

=== Configuring automatic parking and recharging

By default, idle vehicles remain where they are after processing their last transport order.
You can change this in the kernel's configuration file:

* To order vehicles to charging locations automatically, set the configuration parameter `defaultdispatcher.rechargeIdleVehicles` to `true`.
  The default dispatcher will then look for locations at which the idle vehicle's recharge operation is possible and create orders to send it to such a location (if unoccupied).
  (Note that the string used for the operation is driver-specific.)
* To order vehicles to parking positions automatically, set the configuration parameter `defaultdispatcher.parkIdleVehicles` to `true`.
  The default dispatcher will then look for unoccupied parking positions and create orders to send the idle vehicle there.

=== Selecting the cost factors used for routing

The default router can evaluate the costs for routes based on different factors.
You can select which factors should be taken into account by setting the configuration parameter `defaultrouter.shortestpath.edgeEvaluators` in the kernel's configuration file to one or more of the following key words (separated by commas):

* `HOPS`: Routing costs are measured by the number of hops/paths travelled along the route.
* `DISTANCE`: Routing costs are measured by the sum of the lengths of paths travelled.
* `TRAVELTIME`: Routing costs are measured by the sum of the times required for travelling each path on a route.
The travel times are computed using the length of the respective path and the maximum speed with which a vehicle may move on it.
* `EXPLICIT`: Routing costs are measured by the sum of the costs explicitly specified by the modelling user.
  Explicit costs can be specified for every single path in the model using the plant overview client.
  (Select a path and set its btn:[Costs] property to an arbitrary integer value.)

NOTE: When specifying more than one of these key words, the respective costs computed are added up.
For example, when set to `"DISTANCE, TRAVELTIME"`, costs for routes are computed as the sum of the paths' lengths and the time a vehicle needs to pass it.
If none of these entries is set, costs for routes are computed by the paths' lengths by default (`DISTANCE`).

=== Configuring order pool cleanup

By default, openTCS checks every minute for finished or failed transport orders that are older than 24 hours.
These orders are removed from the pool.
To customize this behaviour, do the following:

. Set the configuration entry `orderpool.sweepInterval` to a value according to your needs.
  The default value is 60.000 (milliseconds, corresponding to an interval of one minute).
. Set the configuration entry `orderpool.sweepAge` to a maximum age of finished orders according to your needs.
  The default value is 86.400.000 (milliseconds, corresponding to 24 hours that a finished order should be kept in the pool).

=== Using model element properties for project-specific data

Every object in the plant model - i.e. points, paths, locations, location types and vehicles - can be augmented with arbitrary project-specific data that can be used, e.g. by vehicle drivers, custom client applications, etc..
Possible uses for such data could be informing the vehicle driver about additional actions to be performed by a vehicle when moving along a path in the model (e.g. flashing direction indicators, displaying a text string on a display, giving an acoustic warning) or controlling the behaviour of peripheral systems (e.g. automatic fire protection gates).

The data can be stored in properties, i.e. key-value pairs attached to the model elements, where both the key and the corresponding value are text strings.
These key-value pairs can be created and edited using the plant overview client:
Simply select the model element you want to add a key-value pair to and click into the value field labelled btn:[Miscellaneous] in the properties table.
In the dialog shown, set the key-value pairs you need to store your project-specific information.

NOTE: For your project-specific key-value pairs, you may specify arbitrary keys.
openTCS itself will not make any use of this data; it will merely store it and provide it for custom vehicle drivers and/or other extensions.
You should, however, not use any keys starting with `"tcs:"` for storing project-specific data.
Any keys with this prefix are reserved for official openTCS features, and using them could lead to collisions.
