
[appendix]
== Questions and Answers

=== Plant models

==== How can I migrate plant models created with openTCS before version 3.0?

. Backup the contents of the kernel directory's `data/` subdirectory.
It contains subdirectories with a plant model in a `model.xml` file each.
. Clear the kernel's `data/` directory by removing all its subdirectories.
. Copy one of the `model.xml` files from the backup directories back to the `data/` directory, so that it contains only this single plant model.
+
_Example:
Assuming your `data/` directory contains three model subdirectories `modelA`, `modelB` and `modelC`.
After step one, the three model directories should have been copied to another location.
After step two, the `data/` directory should be empty and after step three, it should contain only the `model.xml` from directory `modelA`._
. Start the kernel and have it load your model.
Then start the plant overview client in modelling mode and select menu:File[Load current kernel model] from its menu to read the model data from the kernel.
. In the plant overview client, select menu:File[Save Model] or menu:File[Save Model As] from the menu.
The plant overview client will persist the model data in a file with the given name and the extension `.opentcs`.
+
_Example: Following the previous example a file with the name `modelA.opentcs` should exist now._
. Delete the `model.xml` file you just moved to the `data/` directory of the kernel.
The migration of this plant model is finished.
. Shut down the kernel, go back to step three and repeat the procedure for the remaining models that you want to migrate.
+
_Example: Follow steps 3 - 7 with `modelB` and `modelC` instead of `modelA`._

==== Why are all transport orders marked `UNROUTABLE` when I only have reporting points in my model?

Vehicles are not allowed to stop at reporting points.
Hence at least the starting point and the endpoint (usually linked to a location) of a route must be halt points to make routing possible.

==== How can I create curved paths between two points?

Select btn:[Bezier] from the path tools and connect two points by clicking on the first point, dragging the mouse to the second point and releasing the mouse button there.
Then activate the selection tool and click on the previously created bezier path.
Two blue control points will appear.
Drag the control points to change the shape of the path.

==== Why do points have two sets of coordinates (model and layout)?

The openTCS kernel itself works with a logical driving course model - geometric attributes of e.g. points and paths are not relevant for its core functionality.
It may, however, have to provide (real/physical) coordinates of a destination point to a vehicle, depending on the way the vehicle's navigation works.
With openTCS, these are called the __model coordinates__.

The __layout coordinates__, on the other hand, are coordinates that are used merely for visualizing the driving course in the plant overview.
These coordinates will probably be the same as the model coordinates in most cases, but they may differ, e.g. in cases where the driving course is supposed to be modelled/displayed in a distorted way.

=== Transport orders

==== How can I set priorities for transport orders?

With openTCS, transport orders do not have a priority attribute.
That is because a transport order's priority may change over time or when other transport orders are added.

In the end, a single transport order's effective priority depends on the dispatcher implementation used.
With openTCS's default dispatcher, transport orders' __deadline__ attributes are intended to be used for prioritizing - the sooner the deadline, the higher an order's effective priority.
To give a transport order a higher priority from the beginning, you can set its deadline to something earlier than all other orders' deadlines, e.g. to "right now" or a point of time in the past.
