== Development with openTCS in general

=== System requirements

The openTCS source code is written in Java.
To compile it, you need a Java Development Kit (JDK) 1.8.
To run the resulting binaries, you need a Java Runtime Environment (JRE) 1.8.
All other required libraries are included in the openTCS distribution or will be downloaded automatically when building it from source code.

=== Available artifacts and API compatibility

The openTCS project publishes artifacts for releases via link:https://bintray.com/bintray/jcenter[JCenter], so you can easily integrate them with build systems such as Gradle or Maven.
In Gradle build scripts, for example, use something like the following to integrate an openTCS library:

[source, groovy, subs="attributes"]
----
repositories {
  jcenter()
}

dependencies {
  compile group: 'org.opentcs', name: '${ARTIFACT}', version: '{project-version}'
}
----

Set the version number of the openTCS release you actually want to work with, and select the appropriate `${ARTIFACT}` name from the following table:

[cols="1,1,2", options="header"]
.Artifacts published by the openTCS project
|===

|Artifact name |API compatibility between minor releases |Content

|`opentcs-api-base`
|Yes
|The base API for clients and extensions.
This is what most developers probably want to use.

|`opentcs-api-injection`
|Yes
|API interfaces and classes used for dependency injection within the kernel and plant overview applications.
This is required in integration projects customizing these applications, e.g. adding components like vehicle driver implementations.

|`opentcs-common`
|No
|A collection of utility classes used by openTCS components.

|`opentcs-impl-configuration-cfg4j`
|No
|An implementation of the base API's configuration interfaces based on cfg4j.

|`opentcs-kernel-extension-http-services`
|No
|A kernel extension providing the web API implementation.

|`opentcs-kernel-extension-rmi-services`
|No
|A kernel extension providing the RMI interface implementation.

|`opentcs-kernel-extension-statistics`
|No
|A kernel extension providing the statistics collection implementation.

|`opentcs-kernel-extension-tcp-host-interface`
|No
|A kernel extension providing the (deprecated) TCP/IP host interface implementation.

|`opentcs-plantoverview-panel-loadgenerator`
|No
|The load generator panel implementation for the plant overview.

|`opentcs-plantoverview-panel-resourceallocation`
|No
|The resource allocation panel implemenation for the plant overview.

|`opentcs-plantoverview-panel-statistics`
|No
|The statistics panel implementation for the plant overview.

|`opentcs-plantoverview-themes-default`
|No
|The default themes implementation for the plant overview.

|`opentcs-commadapter-loopback`
|No
|A very basic vehicle driver simulating a virtual vehicle.

|`opentcs-strategies-default`
|No
|The default implementations of strategies that are used by the kernel application.

|`opentcs-kernel`
|No
|The kernel application.

|`opentcs-kernelcontrolcenter`
|No
|The kernel control center application.

|`opentcs-plantoverview`
|No
|The plant overview application.

|===

Note that only the basic API libraries provide a documented API that the openTCS developers try to keep compatible between minor releases.
(For these libraries, the rules of https://semver.org/[semantic versioning] are applied.)
All other artifacts' contents can and will change regardless of any compatibility concerns, so if you use these and switch to a different version of openTCS, you may have to adjust and recompile your code.

=== Third-party dependencies

The kernel and the client applications depend on the following external frameworks and libraries:

* SLF4J (https://www.slf4j.org/):
  A simple logging facade to keep the actual logging implementation replaceable.
* Google Guice (https://github.com/google/guice):
  A light-weight dependency injection framework.
* Cfg4j (http://www.cfg4j.org/):
  A configuration library supporting binding interfaces.
* Google Guava (https://github.com/google/guava):
  A collection of small helper classes and methods.

The kernel application also depends on the following libraries:

* JGraphT (http://jgrapht.org/):
  A library for working with graphs and using algorithms on them.
* Spark (http://sparkjava.com/):
  A framework for creating web applications.
* Jackson (https://github.com/FasterXML/jackson):
  Provides JSON bindings for Java objects.
* JDOM (http://www.jdom.org/):
  A library for reading and writing XML data.

The plant overview application has the following additional dependencies:

* JHotDraw (http://www.jhotdraw.org/):
  A framework for drawing graph structures (like driving course models).
* Docking Frames (http://www.docking-frames.org/):
  A framework for docking and undocking of GUI panels

For automatic tests, the following dependencies are used:

* JUnit (https://junit.org/):
  A simple unit-testing framework.
* Mockito (http://mockito.org/):
  A framework for creating mock objects.
* Hamcrest (http://hamcrest.org/):
  A framework for assertion matchers that can be used in tests.

The artifacts for these dependencies are downloaded automatically when building the applications.

=== Modularity and extensibility

The openTCS project heavily relies on link:https://github.com/google/guice[Guice] for dependency injection and wiring of components as well as for providing plugin-like extension mechanisms.
In the injection API, relevant classes can be found in the package `org.opentcs.customizations`.
For examples, see <<Customizing and extending the kernel application>>, <<Customizing and extending the plant overview application>> and <<Customizing and extending the control center application>>.

=== Logging

The code in the official openTCS distribution uses http://www.slf4j.org/[SLF4J] for logging.
Thus, the actual logging implementation is easily interchangeable by replacing the SLF4J binding in the respective application's classpath.
The kernel and plant overview client applications come with SLF4J's bindings for `java.util.logging` by default.
For more information on how to change the actual logging implementation, e.g. to use log4j, please see the SLF4J documentation.

=== Working with the openTCS source code

The openTCS project itself uses link:https://gradle.org/[Gradle] as its build management tool.
To build openTCS from source code, just run `gradlew build` from the source distribution's main directory.
For details on how to work with Gradle, please see link:https://docs.gradle.org/[its documentation].

These are the main Gradle tasks of the root project you need to know to get started:

* `build`: Compiles the source code of all subprojects.
* `release`: Builds and packages all system components to a distribution in `build/`.
* `clean`: Cleans up everything produced by the other tasks.

To work with the source code in your IDE, see the IDE's documentation for Gradle integration.
There is no general recommendation for any specific IDE.
Note, however, that the openTCS source code contains GUI components that have been created with the NetBeans GUI builder.
If you want to edit these, you may want to use the NetBeans IDE.

In case you use NetBeans, install the link:http://plugins.netbeans.org/plugin/44510/gradle-support[Gradle Support] plugin from the NetBeans plugin portal.
You should then be able to open the source distribution's root directory as a Gradle project and compile and run the components from within NetBeans.

=== openTCS kernel APIs

openTCS provides the following APIs to interact with the kernel:

* The kernel's Java API for both extending the kernel application as well as interfacing with it via RMI.
  See <<section-kernel-api>> for details.
* A web API for interfacing with the kernel via HTTP calls.
  See the separate interface documentation that is part of the openTCS distribution for details.
* A legacy TCP/IP-based interface for creating transport orders and fetching status information.
  See <<section-tcp-host-interfaces>> for details. +
  _Note that this interface is deprecated in favour of the web API and will be removed with the release of openTCS 5.0._
