
== The kernel's web API

In addition to the Java-specific kernel interface, openTCS provides a web API.
This interface offers the following functionality:

* Transport orders can be created.
* Transport orders can be withdrawn.
* Status updates for transport orders and vehicles can be retrieved (with long polling).

Bodies of HTTP requests and responses, where applicable, are JSON structures.
JSON schemas describing the structures are part of the developer documentation in the openTCS binary distribution.
The encoding used may be UTF-8, UTF-16 or UTF-32.
Where time stamps are used, they are encoded using https://en.wikipedia.org/wiki/ISO_8601[ISO 8601]; the time zone used is UTC.

The TCP port to be used for the HTTP requests is configuration-dependent; by default, it is 55200.
The paths for the respective functions are described in the following sections.

By default, requests are accepted without requiring any authentication.
Optionally, an access key can be set in the kernel configuration.
The configured value is then expected to be sent by the client in an HTTP header named `X-Api-Access-Key`.

// counter for labeling and referencing the coding examples
:http-example-label: {counter:http-example}

=== Creating a transport order

* Path: `/v1/transportOrders/<NAME>`
* HTTP method: `POST`
* Query parameters: None
* Example URL: \http://opentcs.example.com:55200/v1/transportOrders/TOrder-1234

The request body is expected to contain a description of the transport order to be created.
It should contain something like this:

[#example.httpcreateorder, reftext='Example {http-example-label}']
[[example.httpcreateorder]]
.Example {http-example-label}: JSON structure for creating a transport order
[source, json] 
----
include::{samples}/sample-create-order.json[]
----

The response signals success with an HTTP status code of 200 (OK).
The response's body is empty.

=== Withdrawing a transport order by its name

* Path : `/v1/transportOrders/<NAME>/withdrawal`
* HTTP method: `POST`
* Query parameters:
** immediate (boolean, optional):
   Whether the transport order should be aborted as quickly as possible.
   (Default: `false`)
** disableVehicle (boolean, optional):
   Whether the processing vehicle should not be assigned any further transport order.
   (Default: `false`)
* Example URLs:
** \http://opentcs.example.com:55200/v1/transportOrders/TOrder-0075/withdrawal
** \http://opentcs.example.com:55200/v1/transportOrders/TOrder-0075/withdrawal?immediate=true
** \http://opentcs.example.com:55200/v1/transportOrders/TOrder-0075/withdrawal?disableVehicle=true

The request's body is ignored.
The response's body is empty.

=== Withdrawing a transport order by processing vehicle

* Path : `/v1/vehicles/<NAME>/withdrawal`
* HTTP method: `POST`
* Query parameters:
** immediate (boolean, optional):
   Whether the transport order should be aborted as quickly as possible.
   (Default: `false`)
** disableVehicle (boolean, optional):
   Whether the processing vehicle should not be assigned any further transport order.
   (Default: `false`)
* Example URLs:
** \http://opentcs.example.com:55200/v1/vehicles/Vehicle-0001/withdrawal
** \http://opentcs.example.com:55200/v1/vehicles/Vehicle-0001/withdrawal?immediate=true
** \http://opentcs.example.com:55200/v1/vehicles/Vehicle-0001/withdrawal?disableVehicle=true

The request's body is ignored.
The response's body is empty.

=== Retrieving status updates

* Path: `/v1/events`
* HTTP method: `GET`
* Query parameters
** minSequenceNo (integer, optional):
   The minimum sequence number of events to be retrieved.
   (Default: no minimum)
** maxSequenceNo (integer, optional):
   The maximum sequence number of events to be retrieved.
   (Default: no maximum)
** timeout (integer, optional):
   The time (in milliseconds) to wait for events to arrive if there currently aren't any events to be returned.
   May not be greater than 10000.
   (Default: 1000)
* Examples URLs:
** \http://opentcs.example.com:55200/v1/events
** \http://opentcs.example.com:55200/v1/events?timeout=5000
** \http://opentcs.example.com:55200/v1/events?minSequenceNo=100
** \http://opentcs.example.com:55200/v1/events?minSequenceNo=100&maxSequenceNo=200

The request's body is ignored.
The response's body looks like the following:

[#example.httpfetchevents, reftext='Example {http-example-label}']
[[example.httpfetchevents]]
.Example {http-example-label}: JSON structure for fetching events/updates
[source, json] 
----
include::{samples}/sample-status.json[]
----

