
== Generating an integration project

The openTCS source code distribution provides a Gradle task to generate so called _integration projects_.
This task generates a new skeleton Gradle project that can be used to get started customizing and extending openTCS components.

To generate an integration project, execute the following command from the source project's root directory:

[source, shell]
----
gradlew createIntegrationProject [<options>]
----

The following options are available:

[cols="1,1,1", options="header"]
.Available options for creating integration projects
|===

|Option |Description |Default value

|`-PcustomizationName=<propertyValue>`
|The customization name of the generated integration project.
The generated project's name will be `openTCS-Integration-<customizationName>`.
|`"MyProject"`

|`-PbaselineVersion=<propertyValue>`
|The version of the openTCS baseline project the generated integration project depends on.
|A snapshot of the distribution the task is provided by.

|`-PjavaFilePrefix=<propertyValue>`
|The prefix used for Java files generated by the task.
|`"Custom"`

|===

The integration project will be generated in the distribution's `build` directory.
(Make sure you copy it somewhere else before running the root project's `clean` task the next time.)
