== Application configuration

As described in the openTCS User's Guide, the openTCS Kernel, Kernel Control Center, Model Editor and Operations Desk applications read their configurations from properties files.
This functionality is provided by the link:https://github.com/gestalt-config/gestalt[gestalt] library or alternatively the link:http://www.cfg4j.org/[cfg4j] library.
Which library a particular application uses can be configured by setting the system property `opentcs.configuration.provider` to one of the following values:

* `gestalt`: The gestalt library is used.
  This is the default.
* `cfg4j`: The cfg4j library is used.

NOTE: Support for cfg4j is scheduled for removal with openTCS 6.

=== Supplementing configuration sources using gestalt

It is possible to register additional configuration sources, e.g. for reading configuration data from network resources or files in different formats.
The mechanism provided by `java.util.ServiceLoader` is used for this.
The following steps are required for registering a configuration source:

. Build a JAR file with the following content:
.. An implementation of `org.opentcs.configuration.gestalt.SupplementaryConfigSource`.
   This interface is part of the `opentcs-impl-configuration-gestalt` artifact, which must be on your project's classpath.
.. A plain text file named `META-INF/services/org.opentcs.configuration.gestalt.SupplementaryConfigSource`.
   This file should contain a single line of text with the fully qualified class name of your implementation.
. Ensure that the JAR file is part of the classpath when you start the respective application.

It is possible to register multiple supplementary configuration sources this way.

The configuration entries provided by any registered supplementary configuration source may override configuration entries provided by the properties files that are read by default.
Note that the order in which these additional configuration sources are processed is unspecified.

For more information on how the automatic registration works, see the documentation of `java.util.ServiceLoader` in the Java class library.

=== Supplementing configuration sources using cfg4j

It is possible to register additional configuration sources, e.g. for reading configuration data from network resources or files in different formats.
The mechanism provided by `java.util.ServiceLoader` is used for this.
The following steps are required for registering a configuration source:

. Build a JAR file with the following content:
.. An implementation of `org.opentcs.configuration.cfg4j.SupplementaryConfigurationSource`.
   This interface is part of the `opentcs-impl-configuration-cfg4j` artifact, which must be on your project's classpath.
.. A plain text file named `META-INF/services/org.opentcs.configuration.cfg4j.SupplementaryConfigurationSource`.
   This file should contain a single line of text with the fully qualified class name of your implementation.
. Ensure that the JAR file is part of the classpath when you start the respective application.

It is possible to register multiple supplementary configuration sources this way.

The configuration entries provided by any registered supplementary configuration source may override configuration entries provided by the properties files that are read by default.
Note that the order in which these additional configuration sources are processed is unspecified.

For more information on how the automatic registration works, see the documentation of `java.util.ServiceLoader` in the Java class library.
