/**
 * Copyright (c) The openTCS Authors.
 *
 * This program is free software and subject to the MIT license. (For details,
 * see the licensing information (LICENSE.txt) you should have received with
 * this copy of the software.)
 */
package org.opentcs.documentation;

import java.util.Collections;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import org.opentcs.access.to.order.DestinationCreationTO;
import org.opentcs.access.to.order.OrderSequenceCreationTO;
import org.opentcs.access.to.order.TransportOrderCreationTO;
import org.opentcs.components.kernel.services.InternalTransportOrderService;
import org.opentcs.components.kernel.services.TransportOrderService;
import org.opentcs.data.model.Location;
import org.opentcs.data.model.LocationType;
import org.opentcs.data.order.DriveOrder;
import org.opentcs.data.order.OrderSequence;
import org.opentcs.data.order.TransportOrder;

/**
 * Test for the developers asciidoc documentation to show how a tranport order sequence is created.
 * This test has no meaning and it just exists for the documentation to refer to and to guarantee
 * an example that compiles.
 *
 * @author Mats Wilhelm (Fraunhofer IML)
 */
public class CreateTransportOrderSequenceTest {

  private TransportOrderService orderService;

  @BeforeEach
  public void setUp() {
    orderService = mock(InternalTransportOrderService.class);
    when(orderService.createOrderSequence(any(OrderSequenceCreationTO.class)))
        .thenReturn(new OrderSequence("OrderSequence"));
    when(orderService.createTransportOrder(any(TransportOrderCreationTO.class)))
        .thenReturn(new TransportOrder(
            "Transportorder",
            Collections.singletonList(new DriveOrder(
                new DriveOrder.Destination(getSampleDestinationLocation().getReference())
                    .withOperation("some operation")))));
  }

  @Test
  public void demoCreateOrderSequence() {
    // Note: Keep these lines to a maximum of 80 characters for the documentation!
    // tag::documentation_createTransportOrderSequence[]
    // Create an order sequence description, providing a name.
    OrderSequenceCreationTO sequenceTO
        = new OrderSequenceCreationTO("MyOrderSequence");
    // Optionally, express that the full name of the sequence should be
    // generated by the kernel. (If you do not do this, you need to ensure that
    // the name of the order sequence given above is unique.)
    sequenceTO = sequenceTO.withIncompleteName(true);
    // Optionally, set the sequence's failure-fatal flag:
    sequenceTO = sequenceTO.withFailureFatal(true);

    // Get a TransportOrderService and ask it to create an order sequence using
    // the given description.
    TransportOrderService transportOrderService
        = getATransportOrderServiceReference();
    OrderSequence orderSequence
        = transportOrderService.createOrderSequence(sequenceTO);

    // Describe the transport order as usual, ...
    TransportOrderCreationTO orderTO
        = new TransportOrderCreationTO(
            "MyOrder",
            List.of(
                new DestinationCreationTO("Some location", "Some operation")
            )
        )
            .withIncompleteName(true);
    // ...but set the wrapping sequence's name to associate the transport order
    // with the order sequence.
    orderTO = orderTO.withWrappingSequence(orderSequence.getName());

    // Create the transport order using the TransportOrderService.
    transportOrderService.createTransportOrder(orderTO);

    // Create and add more orders to the order sequence as necessary.
    // Eventually, set the order sequence's complete flag to indicate that no
    // further transport orders will be added to it.
    transportOrderService.markOrderSequenceComplete(
        orderSequence.getReference()
    );
    // end::documentation_createTransportOrderSequence[]
  }

  private Location getSampleDestinationLocation() {
    return new Location("Location",
                        new LocationType("LocationType").getReference());
  }

  private TransportOrderService getATransportOrderServiceReference() {
    return orderService;
  }
}
